### ISSUE TITLE
Exception during paring

### ISSUE THREAD

**Issue by utech626** [TheGeneGenieProject/GeneGenie.Gedcom#56]
GEDCOM Source Application: RootsMagic
Exception 
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.get_Item(Int32 index)
   at GeneGenie.Gedcom.Parser.GedcomRecordReader.ReadSourceRecord()
   at GeneGenie.Gedcom.Parser.GedcomRecordReader.Parser_TagFound(Object sender, EventArgs e)
   at GeneGenie.Gedcom.Parser.GedcomParser.GedcomParse(String data)
   at GeneGenie.Gedcom.Parser.GedcomRecordReader.ReadGedcom(String gedcomFile)
   at GeneGenieReader.Program.Main(String[] args) in E:\TFSSource\Demo\GeneGenieReader\GeneGenieReader\Program.cs:line 19

			// _ParseState.PreviousLevel + 3)
			else if ((!string.IsNullOrEmpty(m_parseState.PreviousTag)) && m_level == sourceRecord.Level + 3)
			{
				GedcomRecordedEvent recordedEvent = sourceRecord.EventsRecorded[sourceRecord.EventsRecorded.Count - 1];

				switch (m_tag)

Input GEDCOM:
0 @S1@ SOUR
1 ABBR GEDCOM file imported on 11 March 2019
1 TITL GEDCOM file submitted by XXXXXX, XXXXXXX. Imp
2 CONC orted on 11 March 2019.
1 _SUBQ GEDCOM file submitted by XXXX, XXXXXXX. Imp
2 CONC orted on 11 March 2019.
1 _BIBL GEDCOM file, XXXXXXX.
1 _TMPLT
2 TID 0
2 FIELD  <=== ERRROR Here
3 NAME Footnote
3 VALUE GEDCOM file submitted by XXXXXXX, XXXXXXXX. Imp
4 CONC orted on 11 March 2019.
2 FIELD
3 NAME ShortFootnote
3 VALUE GEDCOM file submitted by XXXXXXX, XXXXXX. Imp
4 CONC orted on 11 March 2019.
2 FIELD
3 NAME Bibliography
3 VALUE GEDCOM file, XXXXXX.

**Comment by RyanONeill1970** [comment]
Thanks for this. I can see the error, on first look it seems to be because of the non-standard tags used by Roots Magic.

I don't know if it is the _SUBQ, _BIBL, _TMPLT, TID or FIELD tags or a combination of all of them.

I need to find those tag definitions and ensure they are mapped to standard ones of the same meaning, can you elaborate on what TID and FIELD do? They are not present in the list here (http://www.gencom.org.nz/GEDCOM_tags.html).

**Comment by RyanONeill1970** [comment]
I've also just found the below from (https://genealogytools.com/replacing-family-tree-maker-part-3-importing-your-ftm-tree-into-rootsmagic-7/).

> – Includes custom fields in SOURce records that probably will not be read by most other systems, like _BIBL, SUBQ, _TMPLT, FIELD, TID, and VALUE. Most likely these fields are only useful for other RootsMagic users, and it would be better for them to exchange RM rather than GEDCOM files.

Still not sure whether to preserve or ignore these.

**Comment by utech626** [comment]
Ryan,

Thanks for your reply, I have done some more research. It seems they are specific RootsMagic tags. On the export menu there is an option, ‘Extra Details (RM Specific)’, this option is checked by default. If I uncheck this option, the GEDCOM file imports correctly.

There is a discussion on the RootsMagic tag problem here:
http://forums.rootsmagic.com/index.php?/topic/14408-a-better-export/

Bob Brown
